import { Property, PropertyType, MaintenanceStatus } from './types';

export const DEMO_PROPERTIES: Property[] = [
  {
    id: 'prop_real_1',
    address: '139 Vicarage Lane (E15 4HJ)',
    postcode: 'E15 4HJ',
    type: PropertyType.FLAT,
    imageUrl: 'https://picsum.photos/800/600?random=1',
    purchaseDate: '2010-01-01',
    owner: 'R. Khan',
    description: 'Residential single-let property.',
    currentValuation: 170000,
    mortgage: {
      lenderName: 'Lender',
      termYears: 25,
      fixedRateExpiry: '2025-01-01',
      monthlyPayment: 500,
      interestRate: 3.5,
      type: 'Fixed'
    },
    utilities: [],
    productInsurances: [],
    tenants: [],
    documents: [],
    transactions: [],
    maintenanceTickets: [],
    coordinates: { lat: 51.5369, lng: 0.0076 }
  },
  {
    id: 'prop_real_2',
    address: '80 Vernon Road (E15 2DG)',
    postcode: 'E15 2DG',
    type: PropertyType.FLAT,
    imageUrl: 'https://picsum.photos/800/600?random=2',
    purchaseDate: '2012-01-01',
    owner: 'R. Khan',
    description: 'Residential single-let property.',
    currentValuation: 250000,
    mortgage: {
      lenderName: 'Lender',
      termYears: 25,
      fixedRateExpiry: '2026-01-01',
      monthlyPayment: 600,
      interestRate: 4.0,
      type: 'Fixed'
    },
    utilities: [],
    productInsurances: [],
    tenants: [],
    documents: [],
    transactions: [],
    maintenanceTickets: [],
    coordinates: { lat: 51.5312, lng: 0.0028 }
  },
  {
    id: 'prop_real_3',
    address: 'Flat 3, SG4 9SA',
    postcode: 'SG4 9SA',
    type: PropertyType.FLAT,
    imageUrl: 'https://picsum.photos/800/600?random=3',
    purchaseDate: '2015-01-01',
    owner: 'R. Khan',
    description: 'Residential flat.',
    currentValuation: 180000,
    utilities: [],
    productInsurances: [],
    tenants: [],
    documents: [],
    transactions: [],
    maintenanceTickets: []
  },
  {
    id: 'prop_real_4',
    address: '27A, SG1 1PS',
    postcode: 'SG1 1PS',
    type: PropertyType.FLAT,
    imageUrl: 'https://picsum.photos/800/600?random=4',
    purchaseDate: '2018-01-01',
    owner: 'R. Khan',
    description: 'Residential property.',
    currentValuation: 175000,
    utilities: [],
    productInsurances: [],
    tenants: [],
    documents: [],
    transactions: [],
    maintenanceTickets: []
  }
];